#!/usr/bin/exec-suid -- /usr/bin/python3.12 -I
import sys
import os
import re

sys.path.append('/challenge')
from pacePythonTester import ExecutionAgent as ex

def print_flag():
    try:
        with open("/flag", "r") as f:
            print("Cool function! Here's the flag: ")
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

def run_and_check_script(user_script_path):
    for a in [10]:
        # Make sure that they print all the numbers 1-10
        text = re.compile('\n'.join([str(i) for i in range(1,a+1)]), re.IGNORECASE)

        # Run their program with the test case of Greg
        try:
            stdout, stderr = ex.run(user_script_path)
        except TypeError as e:
            """ Issue with noneType return """
            print("Error:", e)
            exit()

        # Set up to match all cases of Hello, Greg!
        if not text.search(stdout.strip()):
            print(f"Error: Make sure that you are printing the numbers 1-10")
            exit()

        # Also, verify that they used the text def in the file: lose check for function usage
        if not ex.parse_script(user_script_path, "def "):
            print(f"Error: Make sure that you are using a function to print the numbers")
            exit()

    print_flag()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("You forgot to give me your python file!")
        print("Try running: '/challenge/verify yourFile.py'")
        sys.exit(1)

    user_script_path = sys.argv[1]
    run_and_check_script(user_script_path)
