#!/usr/bin/exec-suid -- /usr/bin/python3.12 -I
import sys
sys.path.append('/challenge')

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

# Add your imports and other code below here
# Add your imports and other code below here
def print_instructions():
    print("Welcome to the Code Cracker challenge!")
    print("You’re investigating a secret.bin")
    print("Search the secret.bin using strings to find the hexadecimal string and decode it for the flag.")

def main():
    print_instructions()

    try:
        answer = input("Enter the flag you found in the secret.bin file: ").strip()
    except KeyboardInterrupt:
        exit(0)

    correct_flag = "FLAG{binary_hunt}"
    if answer == correct_flag:
        print("That is correct!")
        print("\nHere is your final flag!")
        print_flag()
    else:
        print("Ope, that's not quite right. Try running 'strings secret.bin' to find the flag.")

if __name__ == "__main__":
    main()