#!/usr/bin/exec-suid -- /usr/bin/python3.12 -I
import sys
sys.path.append('/challenge')

def print_flag():
    try:
        with open("/flag", "r") as f:
            print(f.read())
    except FileNotFoundError:
        print("Error: Flag file not found.")

# Add your imports and other code below here
def print_instructions():
    print("Enter the flag you found below to unlock the final flag.")

def main():
    print_instructions()

    try:
        answer = input("Enter the flag you found in the vault.zip: ").strip()
    except KeyboardInterrupt:
        exit(0)

    correct_flag = "FLAG{password_cracked}"
    if answer == correct_flag:
        print("That is correct!")
        print("\nHere is your final flag!")
        print_flag()
    else:
        print("Ope, that's not quite right.")

if __name__ == "__main__":
    main()