#!/usr/bin/exec-suid -- /usr/bin/python3 -I
from flask import Flask, render_template

app = Flask(__name__)

@app.route("/")
def feed():
    return render_template('index.html')

if __name__ == "__main__":
    app.run(debug=True)

if __name__ == "__main__":
	app.run()
	
